[global]
line-length = 80
exclude = [
    "crates/switchback-protobuf/tests/fixtures/**",
    "crates/switchback-mdbook/tests/fixtures/golden/**",
]

[MD013]
reflow = true
code-blocks = false
tables = false


