// Generated by `cargo xtask spec-vendor fetch --write-lock`. Do not edit by hand.

pub const AVRO_COMMON_AVROSCHEMA_V1_JSON: MetaSchemaAsset = MetaSchemaAsset { id: "avro-common-avroSchema-v1-json", relative_path: "common/avroSchema_v1.json", source_url: "https://raw.githubusercontent.com/asyncapi/spec-json-schemas/master/common/avroSchema_v1.json" };

pub const AVRO_DEFINITIONS_2_6_0_AVROSCHEMA_V1_JSON: MetaSchemaAsset = MetaSchemaAsset { id: "avro-definitions-2-6-0-avroSchema-v1-json", relative_path: "definitions/2.6.0/avroSchema_v1.json", source_url: "https://raw.githubusercontent.com/asyncapi/spec-json-schemas/master/definitions/2.6.0/avroSchema_v1.json" };

pub const ALL: &[MetaSchemaAsset] = &[AVRO_COMMON_AVROSCHEMA_V1_JSON, AVRO_DEFINITIONS_2_6_0_AVROSCHEMA_V1_JSON];

pub const AVRO_SCHEMA_V1_3_0: MetaSchemaAsset = AVRO_COMMON_AVROSCHEMA_V1_JSON;
pub const AVRO_SCHEMA_V1_2_6: MetaSchemaAsset = AVRO_DEFINITIONS_2_6_0_AVROSCHEMA_V1_JSON;
