// Generated by `cargo xtask spec-vendor fetch --write-lock`. Do not edit by hand.


pub const OPENAPI_OAS_2_0_SCHEMA_2017_08_27: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-2-0-schema-2017-08-27", relative_path: "oas/2.0/schema/2017-08-27", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/2.0/schema/2017-08-27" };

pub const OPENAPI_OAS_3_0_SCHEMA_2021_09_28: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-0-schema-2021-09-28", relative_path: "oas/3.0/schema/2021-09-28", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.0/schema/2021-09-28" };

pub const OPENAPI_OAS_3_0_SCHEMA_2024_10_18: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-0-schema-2024-10-18", relative_path: "oas/3.0/schema/2024-10-18", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.0/schema/2024-10-18" };

pub const OPENAPI_OAS_3_1_SCHEMA_2021_03_02: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-2021-03-02", relative_path: "oas/3.1/schema/2021-03-02", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema/2021-03-02" };

pub const OPENAPI_OAS_3_1_SCHEMA_BASE_2021_03_02: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-base-2021-03-02", relative_path: "oas/3.1/schema-base/2021-03-02", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema-base/2021-03-02" };

pub const OPENAPI_OAS_3_1_SCHEMA_2021_04_15: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-2021-04-15", relative_path: "oas/3.1/schema/2021-04-15", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema/2021-04-15" };

pub const OPENAPI_OAS_3_1_SCHEMA_BASE_2021_04_15: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-base-2021-04-15", relative_path: "oas/3.1/schema-base/2021-04-15", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema-base/2021-04-15" };

pub const OPENAPI_OAS_3_1_SCHEMA_2021_05_20: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-2021-05-20", relative_path: "oas/3.1/schema/2021-05-20", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema/2021-05-20" };

pub const OPENAPI_OAS_3_1_SCHEMA_BASE_2021_05_20: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-base-2021-05-20", relative_path: "oas/3.1/schema-base/2021-05-20", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema-base/2021-05-20" };

pub const OPENAPI_OAS_3_1_SCHEMA_2021_09_28: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-2021-09-28", relative_path: "oas/3.1/schema/2021-09-28", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema/2021-09-28" };

pub const OPENAPI_OAS_3_1_SCHEMA_BASE_2021_09_28: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-base-2021-09-28", relative_path: "oas/3.1/schema-base/2021-09-28", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema-base/2021-09-28" };

pub const OPENAPI_OAS_3_1_SCHEMA_2022_02_27: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-2022-02-27", relative_path: "oas/3.1/schema/2022-02-27", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema/2022-02-27" };

pub const OPENAPI_OAS_3_1_SCHEMA_BASE_2022_02_27: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-base-2022-02-27", relative_path: "oas/3.1/schema-base/2022-02-27", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema-base/2022-02-27" };

pub const OPENAPI_OAS_3_1_SCHEMA_2022_10_07: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-2022-10-07", relative_path: "oas/3.1/schema/2022-10-07", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema/2022-10-07" };

pub const OPENAPI_OAS_3_1_SCHEMA_BASE_2022_10_07: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-base-2022-10-07", relative_path: "oas/3.1/schema-base/2022-10-07", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema-base/2022-10-07" };

pub const OPENAPI_OAS_3_1_SCHEMA_2024_11_14: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-2024-11-14", relative_path: "oas/3.1/schema/2024-11-14", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema/2024-11-14" };

pub const OPENAPI_OAS_3_1_SCHEMA_BASE_2024_11_14: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-base-2024-11-14", relative_path: "oas/3.1/schema-base/2024-11-14", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema-base/2024-11-14" };

pub const OPENAPI_OAS_3_1_SCHEMA_2025_02_13: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-2025-02-13", relative_path: "oas/3.1/schema/2025-02-13", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema/2025-02-13" };

pub const OPENAPI_OAS_3_1_SCHEMA_BASE_2025_02_13: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-base-2025-02-13", relative_path: "oas/3.1/schema-base/2025-02-13", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema-base/2025-02-13" };

pub const OPENAPI_OAS_3_1_SCHEMA_2025_08_31: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-2025-08-31", relative_path: "oas/3.1/schema/2025-08-31", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema/2025-08-31" };

pub const OPENAPI_OAS_3_1_SCHEMA_BASE_2025_08_31: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-base-2025-08-31", relative_path: "oas/3.1/schema-base/2025-08-31", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema-base/2025-08-31" };

pub const OPENAPI_OAS_3_1_SCHEMA_2025_09_15: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-2025-09-15", relative_path: "oas/3.1/schema/2025-09-15", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema/2025-09-15" };

pub const OPENAPI_OAS_3_1_SCHEMA_BASE_2025_09_15: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-base-2025-09-15", relative_path: "oas/3.1/schema-base/2025-09-15", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema-base/2025-09-15" };

pub const OPENAPI_OAS_3_1_SCHEMA_2025_11_23: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-2025-11-23", relative_path: "oas/3.1/schema/2025-11-23", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema/2025-11-23" };

pub const OPENAPI_OAS_3_1_SCHEMA_BASE_2025_11_23: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-schema-base-2025-11-23", relative_path: "oas/3.1/schema-base/2025-11-23", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/schema-base/2025-11-23" };

pub const OPENAPI_OAS_3_1_DIALECT_BASE: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-dialect-base", relative_path: "oas/3.1/dialect/base", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/dialect/base" };

pub const OPENAPI_OAS_3_1_DIALECT_2024_10_25: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-dialect-2024-10-25", relative_path: "oas/3.1/dialect/2024-10-25", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/dialect/2024-10-25" };

pub const OPENAPI_OAS_3_1_DIALECT_2024_11_10: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-dialect-2024-11-10", relative_path: "oas/3.1/dialect/2024-11-10", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/dialect/2024-11-10" };

pub const OPENAPI_OAS_3_1_META_BASE: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-meta-base", relative_path: "oas/3.1/meta/base", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/meta/base" };

pub const OPENAPI_OAS_3_1_META_2024_10_25: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-meta-2024-10-25", relative_path: "oas/3.1/meta/2024-10-25", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/meta/2024-10-25" };

pub const OPENAPI_OAS_3_1_META_2024_11_10: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-1-meta-2024-11-10", relative_path: "oas/3.1/meta/2024-11-10", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.1/meta/2024-11-10" };

pub const OPENAPI_OAS_3_2_SCHEMA_2025_09_17: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-2-schema-2025-09-17", relative_path: "oas/3.2/schema/2025-09-17", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.2/schema/2025-09-17" };

pub const OPENAPI_OAS_3_2_SCHEMA_2025_11_23: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-2-schema-2025-11-23", relative_path: "oas/3.2/schema/2025-11-23", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.2/schema/2025-11-23" };

pub const OPENAPI_OAS_3_2_SCHEMA_BASE_2025_09_17: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-2-schema-base-2025-09-17", relative_path: "oas/3.2/schema-base/2025-09-17", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.2/schema-base/2025-09-17" };

pub const OPENAPI_OAS_3_2_SCHEMA_BASE_2025_11_23: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-2-schema-base-2025-11-23", relative_path: "oas/3.2/schema-base/2025-11-23", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.2/schema-base/2025-11-23" };

pub const OPENAPI_OAS_3_2_DIALECT_2025_09_17: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-2-dialect-2025-09-17", relative_path: "oas/3.2/dialect/2025-09-17", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.2/dialect/2025-09-17" };

pub const OPENAPI_OAS_3_2_META_2025_09_17: MetaSchemaAsset = MetaSchemaAsset { id: "openapi-oas-3-2-meta-2025-09-17", relative_path: "oas/3.2/meta/2025-09-17", source_url: "https://raw.githubusercontent.com/OAI/spec.openapis.org/main/oas/3.2/meta/2025-09-17" };

pub const ALL: &[MetaSchemaAsset] = &[OPENAPI_OAS_2_0_SCHEMA_2017_08_27, OPENAPI_OAS_3_0_SCHEMA_2021_09_28, OPENAPI_OAS_3_0_SCHEMA_2024_10_18, OPENAPI_OAS_3_1_SCHEMA_2021_03_02, OPENAPI_OAS_3_1_SCHEMA_BASE_2021_03_02, OPENAPI_OAS_3_1_SCHEMA_2021_04_15, OPENAPI_OAS_3_1_SCHEMA_BASE_2021_04_15, OPENAPI_OAS_3_1_SCHEMA_2021_05_20, OPENAPI_OAS_3_1_SCHEMA_BASE_2021_05_20, OPENAPI_OAS_3_1_SCHEMA_2021_09_28, OPENAPI_OAS_3_1_SCHEMA_BASE_2021_09_28, OPENAPI_OAS_3_1_SCHEMA_2022_02_27, OPENAPI_OAS_3_1_SCHEMA_BASE_2022_02_27, OPENAPI_OAS_3_1_SCHEMA_2022_10_07, OPENAPI_OAS_3_1_SCHEMA_BASE_2022_10_07, OPENAPI_OAS_3_1_SCHEMA_2024_11_14, OPENAPI_OAS_3_1_SCHEMA_BASE_2024_11_14, OPENAPI_OAS_3_1_SCHEMA_2025_02_13, OPENAPI_OAS_3_1_SCHEMA_BASE_2025_02_13, OPENAPI_OAS_3_1_SCHEMA_2025_08_31, OPENAPI_OAS_3_1_SCHEMA_BASE_2025_08_31, OPENAPI_OAS_3_1_SCHEMA_2025_09_15, OPENAPI_OAS_3_1_SCHEMA_BASE_2025_09_15, OPENAPI_OAS_3_1_SCHEMA_2025_11_23, OPENAPI_OAS_3_1_SCHEMA_BASE_2025_11_23, OPENAPI_OAS_3_1_DIALECT_BASE, OPENAPI_OAS_3_1_DIALECT_2024_10_25, OPENAPI_OAS_3_1_DIALECT_2024_11_10, OPENAPI_OAS_3_1_META_BASE, OPENAPI_OAS_3_1_META_2024_10_25, OPENAPI_OAS_3_1_META_2024_11_10, OPENAPI_OAS_3_2_SCHEMA_2025_09_17, OPENAPI_OAS_3_2_SCHEMA_2025_11_23, OPENAPI_OAS_3_2_SCHEMA_BASE_2025_09_17, OPENAPI_OAS_3_2_SCHEMA_BASE_2025_11_23, OPENAPI_OAS_3_2_DIALECT_2025_09_17, OPENAPI_OAS_3_2_META_2025_09_17];

pub const OAS_3_1_SCHEMA_2025_11_23: MetaSchemaAsset = OPENAPI_OAS_3_1_SCHEMA_2025_11_23;
pub const OAS_3_1_SCHEMA_BASE_2025_11_23: MetaSchemaAsset = OPENAPI_OAS_3_1_SCHEMA_BASE_2025_11_23;
