// Generated by `cargo xtask spec-vendor fetch --write-lock`. Do not edit by hand.


pub const OPENRPC_SPEC_1_3_SCHEMA_JSON: MetaSchemaAsset = MetaSchemaAsset { id: "openrpc-spec-1-3-schema-json", relative_path: "spec/1.3/schema.json", source_url: "https://raw.githubusercontent.com/open-rpc/spec/master/spec/1.3/schema.json" };

pub const OPENRPC_SPEC_1_4_SCHEMA_JSON: MetaSchemaAsset = MetaSchemaAsset { id: "openrpc-spec-1-4-schema-json", relative_path: "spec/1.4/schema.json", source_url: "https://raw.githubusercontent.com/open-rpc/spec/master/spec/1.4/schema.json" };

pub const ALL: &[MetaSchemaAsset] = &[OPENRPC_SPEC_1_3_SCHEMA_JSON, OPENRPC_SPEC_1_4_SCHEMA_JSON];

pub const SCHEMA_1_4: MetaSchemaAsset = OPENRPC_SPEC_1_4_SCHEMA_JSON;
pub const SCHEMA_1_3: MetaSchemaAsset = OPENRPC_SPEC_1_3_SCHEMA_JSON;
